spring.application.name=Product
spring.datasource.url=jdbc:postgresql://localhost:5433/vector_db?TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Transformers Embedding Configuration
spring.ai.transformers.embedding.enabled=true
spring.ai.transformers.embedding.model-url=https://huggingface.co/intfloat/e5-small-v2/resolve/main/model.onnx
spring.ai.transformers.embedding.tokenizer-url=https://huggingface.co/intfloat/e5-small-v2/resolve/main/tokenizer.json